# Generated by Django 3.2.15 on 2022-09-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('sex', models.IntegerField(default=0)),
                ('tips', models.CharField(max_length=120)),
                ('coins', models.IntegerField(default=0)),
                ('avator', models.CharField(max_length=300)),
            ],
        ),
    ]
